# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**You must implement your own work.** You can and are encouraged to use helper libraries like `numpy`, but you must not use 3rd-party libraries or code that solves the assignment for you. *Even if it is properly referenced*, you only get marks for work you have done. If you are unsure, ask on the forum or ask a tutor directly.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For this assignment you will need to submit:
1. The implementation for an agent which can solve sudoku puzzles – this notebook
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests
2. A text file that explains your approach and the decisions you made in your own words – a readme file
 * Submissions that do not include the written section will receive zero marks – **this part is mandatory**
 * You may write your file in plain text (.txt) or [Markdown](https://www.markdownguide.org/basic-syntax/) (.md)
 * To get top marks on this assignment, as well as getting a high grade from your implementation, you must also demonstrate excellent academic presentation in your written section

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

You should also consider what *data structures* you use within your code. Certain algorithms will work much faster with certain data structures, and understanding this is considered part of understanding the algorithm itself. 

I suggest you implement *constraint satisfaction* as it is described in the unit material. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%). There is an example of constraint satisfaction on the eight-queens puzzle, and you could use this as a guide to help you get started.

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (readme file), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [11]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[1], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[1])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[0 9 3 1 5 2 6 0 8]
 [8 6 2 7 0 3 1 9 5]
 [1 5 7 9 8 6 3 2 4]
 [9 7 8 4 2 1 0 3 6]
 [5 0 6 8 3 9 4 1 7]
 [3 4 1 5 6 7 2 8 9]
 [6 1 4 2 7 8 9 5 3]
 [7 3 9 6 1 5 8 4 2]
 [2 8 5 3 9 4 7 6 1]] 

Solution of first sudoku:
[[4 9 3 1 5 2 6 7 8]
 [8 6 2 7 4 3 1 9 5]
 [1 5 7 9 8 6 3 2 4]
 [9 7 8 4 2 1 5 3 6]
 [5 2 6 8 3 9 4 1 7]
 [3 4 1 5 6 7 2 8 9]
 [6 1 4 2 7 8 9 5 3]
 [7 3 9 6 1 5 8 4 2]
 [2 8 5 3 9 4 7 6 1]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [12]:
import numpy as np
import copy
import time
import itertools

def sudoku_solver(sudoku = None, print_flag = False):
    """
    Solves a Sudoku puzzle and returns its unique solution.

    Input
        sudoku : 9x9 numpy array
            Empty cells are designated by 0.

    Output
        9x9 numpy array of integers
            It contains the solution, if there is one. If there is no solution, all array entries should be -1.
    """  
    # Input validation
    if sudoku is None:
        raise ValueError("Initial Sudoku grid not provided")
    if not isinstance(sudoku, np.ndarray):
        raise ValueError("Initial Sudoku grid must be provided as a 9x9 numpy array")
    if len(sudoku)!= 9:
        raise ValueError("Initial Sudoku grid must be provided as a 9x9 numpy array")
    for rows in sudoku:
        if len(rows) != 9:
            raise ValueError("Initial Sudoku grid must be provided as a 9x9 numpy array")
        for col in rows:
            if not (isinstance(col, np.int8) or isinstance(col, np.int16) or isinstance(col, np.int32) or isinstance(col, np.int64)):
                raise ValueError("Cell value must be integers")
            if col > 9 or col < 0:
                raise ValueError("Value out ouf range: Each cell must have a value between 0 and 9 included")
                    
    state = Sudoku_grid(sudoku)
    game = Sudoku_game()
    solFound, result = game.solve(state)
    solved_sudoku = result.get_grid()
    
    if print_flag:
        print(f"Number of explored nodes: {game.explored_nodes}")
        print(f"Solution Tree depth: {game.tree_depth}")
    
    return solved_sudoku

import numpy as np
import copy
import time


class Sudoku_grid:

    def __init__(self, grid=None):
        if grid is None:
            raise ValueError("Initial Sudoku grid not provided")
        # create full domain for all cells
        A = [set([j for j in range(1, 10)]) for i in range(1, 10)]
        B = [set([j for j in range(1, 10)]) for i in range(1, 10)]
        C = [set([j for j in range(1, 10)]) for i in range(1, 10)]
        D = [set([j for j in range(1, 10)]) for i in range(1, 10)]       
        E = [set([j for j in range(1, 10)]) for i in range(1, 10)]
        F = [set([j for j in range(1, 10)]) for i in range(1, 10)]
        G = [set([j for j in range(1, 10)]) for i in range(1, 10)]
        H = [set([j for j in range(1, 10)]) for i in range(1, 10)]
        I = [set([j for j in range(1, 10)]) for i in range(1, 10)]
        
        
        for idx_row, row in enumerate([A, B, C, D, E, F, G, H, I]):
            for idx_col, col in enumerate(row):
                val = int(grid[idx_row][idx_col])
                if val != 0:
                    row[idx_col] = {val}

        # unpack each cell domain                 
        A1, A2, A3, A4, A5, A6, A7, A8, A9 = tuple(A)
        B1, B2, B3, B4, B5, B6, B7, B8, B9 = tuple(B)
        C1, C2, C3, C4, C5, C6, C7, C8, C9 = tuple(C)
        D1, D2, D3, D4, D5, D6, D7, D8, D9 = tuple(D)
        E1, E2, E3, E4, E5, E6, E7, E8, E9 = tuple(E)
        F1, F2, F3, F4, F5, F6, F7, F8, F9 = tuple(F)
        G1, G2, G3, G4, G5, G6, G7, G8, G9 = tuple(G)
        H1, H2, H3, H4, H5, H6, H7, H8, H9 = tuple(H)
        I1, I2, I3, I4, I5, I6, I7, I8, I9 = tuple(I)

        #Create Rows units (top to bottom)
        Row1 = [A1, A2, A3, A4, A5, A6, A7, A8, A9]
        Row2 = [B1, B2, B3, B4, B5, B6, B7, B8, B9]
        Row3 = [C1, C2, C3, C4, C5, C6, C7, C8, C9]
        Row4 = [D1, D2, D3, D4, D5, D6, D7, D8, D9]
        Row5 = [E1, E2, E3, E4, E5, E6, E7, E8, E9]
        Row6 = [F1, F2, F3, F4, F5, F6, F7, F8, F9]
        Row7 = [G1, G2, G3, G4, G5, G6, G7, G8, G9]
        Row8 = [H1, H2, H3, H4, H5, H6, H7, H8, H9]
        Row9 = [I1, I2, I3, I4, I5, I6, I7, I8, I9]

        #Create Columns units (left to rigth)
        Col1 = [A1, B1, C1, D1, E1, F1, G1, H1, I1]
        Col2 = [A2, B2, C2, D2, E2, F2, G2, H2, I2]
        Col3 = [A3, B3, C3, D3, E3, F3, G3, H3, I3]
        Col4 = [A4, B4, C4, D4, E4, F4, G4, H4, I4]
        Col5 = [A5, B5, C5, D5, E5, F5, G5, H5, I5]
        Col6 = [A6, B6, C6, D6, E6, F6, G6, H6, I6]
        Col7 = [A7, B7, C7, D7, E7, F7, G7, H7, I7]
        Col8 = [A8, B8, C8, D8, E8, F8, G8, H8, I8]
        Col9 = [A9, B9, C9, D9, E9, F9, G9, H9, I9]

        #Create Squares units (left to right, top to bottom)
        Sqr1 = [A1, A2, A3, B1, B2, B3, C1, C2, C3]
        Sqr2 = [A4, A5, A6, B4, B5, B6, C4, C5, C6]
        Sqr3 = [A7, A8, A9, B7, B8, B9, C7, C8, C9]
        Sqr4 = [D1, D2, D3, E1, E2, E3, F1, F2, F3]
        Sqr5 = [D4, D5, D6, E4, E5, E6, F4, F5, F6]
        Sqr6 = [D7, D8, D9, E7, E8, E9, F7, F8, F9]
        Sqr7 = [G1, G2, G3, H1, H2, H3, I1, I2, I3]
        Sqr8 = [G4, G5, G6, H4, H5, H6, I4, I5, I6]
        Sqr9 = [G7, G8, G9, H7, H8, H9, I7, I8, I9]

        # Gather all units into a list    
        self.units = [Row1, Row2, Row3, Row4, Row5, Row6, Row7, Row8, Row9,
                      Col1, Col2, Col3, Col4, Col5, Col6, Col7, Col8, Col9,
                      Sqr1, Sqr2, Sqr3, Sqr4, Sqr5, Sqr6, Sqr7, Sqr8, Sqr9]
    
    # Check if the current state is valid
    def is_valid(self):
        for unit in self.units:
            if set() in unit:
                return False
        return True
    
    # Check if the current state is invalid
    def is_invalid(self):
        for unit in self.units:
            if set() in unit:
                return True
        return False

    # Check if the current state is the goal state    
    def is_gloal(self):
        for unit in self.units[0:9]: # no need to check all unit as the first 9 (rows) already cover all possible cell in the grid
            if sum(Sudoku_grid.get_len_domain(unit)) != 9:
                return False
        return True

    # convert the first 9 units into a numpy 9x9 array representing the sudoku grid 
    def get_grid(self):
        grid = []
        rows = copy.deepcopy(self.units[0:9])
        for row in rows:
            len_domain = Sudoku_grid.get_len_domain(row)
            for idx, n in enumerate(len_domain):
                if n > 1:
                    row[idx] = {0}
            grid.append([item for t in row for item in t])
        return np.array(grid)

    def set_failed_grid(self):
        for unit in self.units[0:9]:
            for domain in unit:
                domain.difference_update(domain)
                domain.add(-1)

    @staticmethod
    def get_len_domain(unit):
        return [len(s) for s in unit]


class Sudoku_game():
    def __init__(self):
        self.tree_depth = 0
        self.explored_nodes = 0
        self.constrain_eval = 0
        self.unit_map = {0: [[9, 18], [10, 18], [11, 18], [12, 19], [13, 19], [14, 19], [15, 20], [16, 20], [17, 20]],
                         1: [[9, 18], [10, 18], [11, 18], [12, 19], [13, 19], [14, 19], [15, 20], [16, 20], [17, 20]],
                         2: [[9, 18], [10, 18], [11, 18], [12, 19], [13, 19], [14, 19], [15, 20], [16, 20], [17, 20]],
                         3: [[9, 21], [10, 21], [11, 21], [12, 22], [13, 22], [14, 22], [15, 23], [16, 23], [17, 23]],
                         4: [[9, 21], [10, 21], [11, 21], [12, 22], [13, 22], [14, 22], [15, 23], [16, 23], [17, 23]],
                         5: [[9, 21], [10, 21], [11, 21], [12, 22], [13, 22], [14, 22], [15, 23], [16, 23], [17, 23]],
                         6: [[9, 24], [10, 24], [11, 24], [12, 25], [13, 25], [14, 25], [15, 26], [16, 26], [17, 26]],
                         7: [[9, 24], [10, 24], [11, 24], [12, 25], [13, 25], [14, 25], [15, 26], [16, 26], [17, 26]],
                         8: [[9, 24], [10, 24], [11, 24], [12, 25], [13, 25], [14, 25], [15, 26], [16, 26], [17, 26]],
                         9: [[0, 18], [1, 18], [2, 18], [3, 21], [4, 21], [5, 21], [6, 24], [7, 24], [8, 24]],
                         10: [[0, 18], [1, 18], [2, 18], [3, 21], [4, 21], [5, 21], [6, 24], [7, 24], [8, 24]],
                         11: [[0, 18], [1, 18], [2, 18], [3, 21], [4, 21], [5, 21], [6, 24], [7, 24], [8, 24]],
                         12: [[0, 19], [1, 19], [2, 19], [3, 22], [4, 22], [5, 22], [6, 25], [7, 25], [8, 25]],
                         13: [[0, 19], [1, 19], [2, 19], [3, 22], [4, 22], [5, 22], [6, 25], [7, 25], [8, 25]],
                         14: [[0, 19], [1, 19], [2, 19], [3, 22], [4, 22], [5, 22], [6, 25], [7, 25], [8, 25]],
                         15: [[0, 20], [1, 20], [2, 20], [3, 23], [4, 23], [5, 23], [6, 26], [7, 26], [8, 26]],
                         16: [[0, 20], [1, 20], [2, 20], [3, 23], [4, 23], [5, 23], [6, 26], [7, 26], [8, 26]],
                         17: [[0, 20], [1, 20], [2, 20], [3, 23], [4, 23], [5, 23], [6, 26], [7, 26], [8, 26]],
                         18: [[0, 9], [1, 9], [2, 9], [0, 10], [1, 10], [2, 10], [0, 11], [1, 11], [2, 11]],
                         19: [[0, 12], [1, 12], [2, 12], [0, 13], [1, 13], [2, 13], [0, 14], [1, 14], [2, 14]],
                         20: [[0, 15], [1, 16], [2, 17], [0, 15], [1, 16], [2, 17], [0, 15], [1, 16], [2, 17]],
                         21: [[3, 9], [3, 10], [3, 11], [4, 9], [4, 10], [4, 11], [5, 9], [5, 10], [5, 11]],
                         22: [[3, 12], [3, 13], [3, 14], [4, 12], [4, 13], [4, 14], [5, 12], [5, 13], [5, 14]],
                         23: [[3, 15], [3, 16], [3, 17], [4, 15], [4, 16], [4, 17], [5, 15], [5, 16], [5, 17]],
                         24: [[6, 9], [6, 10], [6, 11], [7, 9], [7, 10], [7, 11], [8, 9], [8, 10], [8, 11]],
                         25: [[6, 12], [6, 13], [6, 14], [7, 12], [7, 13], [7, 14], [8, 12], [8, 13], [8, 14]],
                         26: [[6, 15], [6, 16], [6, 17], [7, 15], [7, 16], [7, 17], [8, 15], [8, 16], [8, 17]]}

    # AC-3 algorithm to maintain arc-consistency between units    
    def ac_3(self, state,first_unit_idx=None, var_idx=None):
        if first_unit_idx is None: #when no info of the latest assignment are given start by adding all units in the queue
            unit_queue = [i for i in range(27)]  
        else: # otherwise start by adding only the units affected by the latest assigmnet
            unit_queue = self.unit_map[first_unit_idx][var_idx] + [first_unit_idx] 
        n_eval = 0
        while len(unit_queue) > 0:
            n_eval += 1
            unit_idx = unit_queue.pop(0)
            unit = state.units[unit_idx]
            start_unit = copy.deepcopy(unit)
            #run all three constraints
            self.naked_single(unit)
            self.hidden_single(unit)
            self.naked_double(unit)
             # Run "hidden double" only if the other constraints did not shrink the domain as it is computationally quite expensive
            if unit == start_unit:
                self.hidden_double(unit)
            if state.is_invalid():
                return n_eval
            if unit != start_unit:
                this_unit_map = self.unit_map[unit_idx]
                for idx, dom in enumerate(unit):
                    if dom != start_unit[idx]:
                        units_2_add = this_unit_map[idx]
                        for new_unit in units_2_add:
                            if new_unit not in unit_queue:
                                unit_queue.append(new_unit)  # adding all units linked to this unit  but in theory i could  look what domains have changed and only get the right indexes
        return n_eval
    
    # Constraint
    def naked_single(self, unit):
        fun = lambda u, val, i: [s.difference_update(val) for idx, s in enumerate(u) if idx != i]
        for idx, domain in enumerate(unit):
            if len(domain) == 1:
                fun(unit, domain, idx)
    
    # Constraint
    def hidden_single(self, unit):
        for idx, domain in enumerate(unit):
            if len(domain) > 1:
                s_test_1 = Sudoku_game.get_test_set_hidden_single(unit, idx)
                if len(domain.difference(s_test_1)) == 1:
                    domain.difference_update(s_test_1)
    
    # Constraint
    def naked_double(self, unit):
        fun = lambda u, val: [s.difference_update(val) for s in u if s != val]
        for idx, domain in enumerate(unit):
            if len(domain) == 2:
                if domain in unit[idx + 1:-1]:
                    fun(unit, domain)
    
    # Constraint                
    def hidden_double(self, unit):
        for idx, domain in enumerate(unit):
            if 2 < len(domain) <= 5:
                hidden_pairs = itertools.combinations(list(domain),2)
                for a,b in hidden_pairs:
                    a_set = {a,}
                    b_set = {b,}
                    a_set_location = [1 if a_set.issubset(s) and len(s) >= 2 else 0 for s in unit]
                    b_set_location = [1 if b_set.issubset(s) and len(s) >= 2 else 0 for s in unit]
                    if a_set_location == b_set_location and sum(a_set_location) == 2:
                        pair_set = a_set.union(b_set)
                        domain.difference_update(domain-pair_set)
                        a_set_location[idx] = 0
                        idx_next_domain= a_set_location.index(1)
                        next_domain = unit[idx_next_domain]
                        next_domain.difference_update(next_domain-pair_set)
                        return

    
    def backtracking(self, state):
        self.explored_nodes = 0
        self.ac_3(state) # start by shrinking the domains of the starting state
        result, depth = self.backtracking_search(state)
        if depth < 0:
            depth = 0
        else:
            depth -= 1
        self.tree_depth = depth
        return result
    
    
    def backtracking_search(self, starting_state):
        self.explored_nodes += 1
        if starting_state.is_invalid():  # Check if consistency is maintained
            return None, -1
        if starting_state.is_gloal():  # Check if this is the goal
            return starting_state, 1
        actions = self.get_actions(starting_state)  #  next best actions inference
        for action in actions:
            tree_depth = 1
            next_state = self.apply_assignment(starting_state, action)  # make assignment and get next state space
            self.ac_3(next_state, action[0],action[1])  # Enforce the constraints
            next_state, incremental_depth = self.backtracking_search(next_state)  # explore the next state space
            tree_depth += incremental_depth
            if next_state is not None and next_state.is_gloal():  # return if the goal has been found.
                return next_state, tree_depth
        return None, incremental_depth
        
    
    # Heuristic to get the next estimated best actions -Approach A1- see readme.md
    def get_actions(self, state):
        actions = []
        units_priority = [sum(Sudoku_grid.get_len_domain(unit)) if sum(Sudoku_grid.get_len_domain(unit)) > 9 else 100
                          for unit in state.units]
        # unit that has the smallest number of free variable in the domain
        best_unit_idx = min(range(len(units_priority)), key=units_priority.__getitem__)
        best_unit = state.units[best_unit_idx]   
        var_priority = [len(var) if len(var) > 1 else 10 for var in best_unit]
        # varialbe that has the smallest number of free values in the domain
        best_var_idx = min(range(len(var_priority)), key=var_priority.__getitem__)
        # available values for the varaible
        values = list(best_unit[best_var_idx])
        value_scores = []
        sorted_values_by_score = []
        # get the score fore each value.
        # The score is calculated as the number of time the value is found across each cell domain
        for val in values:
            val_num = 0
            for unit in state.units[0:9]:
                val_num += sum([1 if val in domain else 0 for domain in unit])
            value_scores.append(val_num)
        # Sort the values assignment by getting first the values that are less frequent across each cell domain ()    
        for i in range(len(value_scores)):
            idx_max_val = min(range(len(value_scores)), key=value_scores.__getitem__)
            sorted_values_by_score.append(values[idx_max_val])
            value_scores[idx_max_val] = 1000
        # Construct the action as tuple (unit, variable, value)    
        for val in sorted_values_by_score:
            actions.append((best_unit_idx, best_var_idx, val))
        return actions
    
    def get_actions_approach_A2(self, state):
        actions = []
        units_priority = [sum(Sudoku_grid.get_len_domain(unit)) if sum(Sudoku_grid.get_len_domain(unit)) > 9 else 100
                          for unit in state.units]
        # unit that has the smallest number of free variable in the domain
        best_unit_idx = min(range(len(units_priority)), key=units_priority.__getitem__)
        best_unit = state.units[best_unit_idx]   
        var_priority = [len(var) if len(var) > 1 else 10 for var in best_unit]
        # varialbe that has the smallest number of free values in the domain
        best_var_idx = min(range(len(var_priority)), key=var_priority.__getitem__)
        # available values for the varaible
        values = list(best_unit[best_var_idx])
        value_scores = []
        sorted_values_by_score = []
        # get the score fore each value.
        # The score is calculated as the number of time the value is found across each cell domain
        for val in values:
            val_num = 0
            for unit in state.units[0:9]:
                val_num += sum([1 if val in domain else 0 for domain in unit])
            value_scores.append(val_num)
        # Sort the values assignment by getting first the values that are less frequent across each cell domain ()    
        for i in range(len(value_scores)):
            idx_max_val = max(range(len(value_scores)), key=value_scores.__getitem__)
            sorted_values_by_score.append(values[idx_max_val])
            value_scores[idx_max_val] = 0
        # Construct the action as tuple (unit, variable, value)    
        for val in sorted_values_by_score:
            actions.append((best_unit_idx, best_var_idx, val))
        return actions
    
    #-Approach B- see readme.md
    def get_actions_approach_B(self, state):
        actions = []
        units_priority = [sum(Sudoku_grid.get_len_domain(unit)) if sum(Sudoku_grid.get_len_domain(unit)) > 9 else 0
                          for unit in state.units]
        # unit that has the smallest number of free variable in the domain
        best_unit_idx = max(range(len(units_priority)), key=units_priority.__getitem__)
        best_unit = state.units[best_unit_idx]   
        var_priority = [len(var) if len(var) > 1 else 0 for var in best_unit]
        # varialbe that has the smallest number of free values in the domain
        best_var_idx = max(range(len(var_priority)), key=var_priority.__getitem__)
        # available values for the varaible
        values = list(best_unit[best_var_idx])
        value_scores = []
        sorted_values_by_score = []
        # get the score fore each value.
        # The score is calculated as the number of time the value is found across each cell domain
        for val in values:
            val_num = 0
            for unit in state.units[0:9]:
                val_num += sum([1 if val in domain else 0 for domain in unit])
            value_scores.append(val_num)
        # Sort the values assignment by getting first the values that are less frequent across each cell domain ()    
        for i in range(len(value_scores)):
            idx_max_val = min(range(len(value_scores)), key=value_scores.__getitem__)
            sorted_values_by_score.append(values[idx_max_val])
            value_scores[idx_max_val] = 1000
        # Construct the action as tuple (unit, variable, value)    
        for val in sorted_values_by_score:
            actions.append((best_unit_idx, best_var_idx, val))
        return actions
    
    # Apply the action to the domain and return a new state 
    def apply_assignment(self, state, action):
        unit_idx, var_idx, value = action
        next_state = copy.deepcopy(state)
        unit = next_state.units[unit_idx]
        unit[var_idx].intersection_update([value])
        return next_state

    
    def solve(self, state):
        result = self.backtracking(state)   
        solFound = True
        if result is None:
            result = Sudoku_grid(np.array([[0 for _ in range(9)] for _ in range(9)]))
            result.set_failed_grid()
            solFound = False
        return solFound, result
    
    @staticmethod
    def get_test_set_hidden_single(domain, idx_avoid):
        s_test = set()
        for idx, s in enumerate(domain):
            if idx != idx_avoid:
                s_test = s_test.union(s)
        return s_test

All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up – many more than 15 of each. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 20 seconds each on the test machine to count as successful – if it takes longer, it will timeout. Note that this is a maximum, not a goal. Higher grades require better performance on harder puzzles. As a very rough benchmark, you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms and data structures. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [21]:
SKIP_TESTS = False

def tests():
    import time
    difficulties = ['very_easy', 'easy', 'medium', 'hard']
    tot_time = 0
    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            exe_time = end_time-start_time
            tot_time += exe_time
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took", exe_time, "seconds to solve.\n")

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        if count < len(sudokus):
            break
    
    print(f"Total_time = {tot_time}")
if not SKIP_TESTS:
    tests()

Testing very_easy sudokus
This is very_easy sudoku number 0
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]]
This is your solution for very_easy sudoku number 0
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.0 seconds to solve.

This is very_easy sudoku number 1
[[0 9 3 1 5 2 6 0 8]
 [8 6 2 7 0 3 1 9 5]
 [1 5 7 9 8 6 3 2 4]
 [9 7 8 4 2 1 0 3 6]
 [5 0 6 8 3 9 4 1 7]
 [3 4 1 5 6 7 2 8 9]
 [6 1 4 2 7 8 9 5 3]
 [7 3 9 6 1 5 8 4 2]
 [2 8 5 3 9 4 7 6 1]]
This is your solution for very_easy sudoku number 1
[[4 9 3 1 5 2 6 7 8]
 [8 6 2 7 4 3 1 9 5]
 [1 5 7 9 8 6 3 2 4]
 [9 7 8 4 2 1 5 3 6]
 [5 2 6 8 3 9 4 1 7]
 [3 4 1 5 6 7 2 8 9]
 [6 1 4 2 7 8 9 5

This is your solution for easy sudoku number 2
[[-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.015625 seconds to solve.

This is easy sudoku number 3
[[9 5 6 3 4 2 0 7 1]
 [2 8 1 6 9 7 5 0 4]
 [4 3 0 8 1 5 9 2 6]
 [7 1 4 2 6 9 3 5 8]
 [5 6 2 7 3 8 4 1 9]
 [8 9 3 1 5 4 7 6 2]
 [3 7 9 4 2 1 6 8 5]
 [0 4 8 5 7 6 1 9 3]
 [0 2 5 9 8 3 2 4 7]]
This is your solution for easy sudoku number 3
[[-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]]
Is your solution correct?
Yes! Correct solution.
Th

 [-1 -1 -1 -1 -1 -1 -1 -1 -1]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.0 seconds to solve.

This is medium sudoku number 3
[[3 5 4 0 9 8 0 6 7]
 [6 1 2 5 3 7 9 8 4]
 [8 9 7 6 0 0 5 0 2]
 [1 6 9 4 0 3 0 0 0]
 [4 2 3 7 5 9 8 1 6]
 [7 0 5 1 6 0 4 2 3]
 [9 0 1 3 2 0 0 4 0]
 [0 3 8 9 0 0 2 7 1]
 [0 4 6 8 7 1 3 0 9]]
This is your solution for medium sudoku number 3
[[-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.0 seconds to solve.

This is medium sudoku number 4
[[1 9 5 8 3 0 0 0 2]
 [6 0 7 2 0 0 0 9 8]
 [2 8 4 7 9 0 0 5 6]
 [5 4 8 9 7 0 2 6 1]
 [0 6 0 4 8 2 5 3 9]
 [9 2 3 1 6 5 4 8 7]
 [8 1 0 3 4 7 6 0 5]
 [3 7 0 5 0 9 8 0 4]
 [0 5 2 0 1 6 9 0 3]]
This is your solution for med

This is your solution for hard sudoku number 2
[[4 2 5 8 1 6 9 7 3]
 [8 9 3 7 5 4 6 2 1]
 [6 1 7 3 2 9 5 4 8]
 [9 4 1 6 8 7 2 3 5]
 [5 8 2 4 3 1 7 6 9]
 [7 3 6 2 9 5 1 8 4]
 [2 7 9 1 4 8 3 5 6]
 [3 5 4 9 6 2 8 1 7]
 [1 6 8 5 7 3 4 9 2]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.0625 seconds to solve.

This is hard sudoku number 3
[[0 0 0 0 0 0 0 5 0]
 [2 0 7 0 0 9 0 0 0]
 [6 0 0 3 5 1 0 0 0]
 [5 0 0 0 0 0 0 1 0]
 [0 0 3 0 0 0 0 0 8]
 [0 0 0 8 2 0 5 3 0]
 [0 0 0 0 7 0 8 0 4]
 [0 0 6 2 0 0 0 0 0]
 [0 8 0 0 0 0 7 0 0]]
This is your solution for hard sudoku number 3
[[8 3 1 7 4 2 6 5 9]
 [2 5 7 6 8 9 1 4 3]
 [6 9 4 3 5 1 2 8 7]
 [5 6 8 9 3 7 4 1 2]
 [4 2 3 1 6 5 9 7 8]
 [1 7 9 8 2 4 5 3 6]
 [9 1 2 5 7 3 8 6 4]
 [7 4 6 2 1 8 3 9 5]
 [3 8 5 4 9 6 7 2 1]]
Is your solution correct?
Yes! Correct solution.
This sudoku took 0.046875 seconds to solve.

This is hard sudoku number 4
[[9 0 7 0 0 0 6 5 1]
 [1 0 5 0 9 0 0 8 0]
 [0 0 0 0 0 0 0 0 0]
 [0 5 0 4 0 0 0 0 0]
 [0 2 0 

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [18]:
def submission_tests():
    import sys
    import pathlib

    fail = False;

    if not SKIP_TESTS:
        fail = True;
        print("You must set the SKIP_TESTS constant to True in the cell above.")

    p1 = pathlib.Path('./readme.txt')
    p2 = pathlib.Path('./readme.md')
    if not (p1.is_file() or p2.is_file()):
        fail = True;
        print("You must include a separate file called readme.txt or readme.md in your submission.")

    p3 = pathlib.Path('./sudoku.ipynb')
    if not p3.is_file():
        fail = True
        print("This notebook file must be named sudoku.ipynb")

    if "sudoku_solver" not in globals():
        fail = True;
        print("You must include a function called sudoku_solver which accepts a numpy array.")
    else: 
        sudoku = np.load("data/very_easy_puzzle.npy")[0]
        solution = np.load("data/very_easy_solution.npy")[0]

        if not np.array_equal(sudoku_solver(sudoku), solution):
            print("Warning:")
            print("Your sudoku_solver function does not correctly solve the first sudoku.")
            print()
            print("Your assignment is unlikely to get any marks from the autograder. While we will")
            print("try to check it manually to assign some partial credit, we encourage you to ask")
            print("for help on the forum or directly to a tutor.")
            print()
            print("Please use the readme file to explain your code anyway.")

    if fail:
        print()
        sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
    else:
        print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
        print("assignment page, without changing any filenames.")
        print()
        print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")
        
submission_tests()

You must set the SKIP_TESTS constant to True in the cell above.



Your submission is not ready! Please read and follow the instructions above.

In [15]:
# This is a TEST CELL. Do not delete or change.